### ISSUE TITLE
About string to int and int to string

### ISSUE THREAD

**Issue by lirunjing-china** [technology-me/Soil#2]
C++14中有内置函数...

**Comment by technology-me** [comment]
o.......

**Comment by technology-me** [comment]
> C ++ 14中有内置函数...

 Ho,i see,are you here now?

**Comment by technology-me** [comment]
> C ++ 14中有内置函数...

How to convert a long type to an int type with c++ 14?

**Comment by technology-me** [comment]
to_string();
